opencobra/optlang

optlang/cplex_interface.py, optlang/glpk_interface.py, optlang/interface.py, optlang/util.py, tests/test_cplex_interface.py
Solver_specific classes inherit from interface.
Replaced __setattr__ hacks with properties.
Added primal rounding to bounds for constraints
=> Small additions from trello

optlang/container.py, optlang/cplex_interface.py, optlang/glpk_interface.py, optlang/interface.py, tests/test_container.py
Everything is accessed by dictionary or list lookups instead of linear
searches. Calling __contains__ still uses linear search, but only if
given value has name attribute.
=> Container refactoring

optlang/cplex_interface.py, optlang/glpk_interface.py, optlang/interface.py, tests/test_cplex_interface.py, tests/test_glpk_interface.py, tests/test_netlib_cplex_interface.py, tests/test_netlib_glpk_interface.py
Furthermore, objective.expression is now determined from solver instance.
=> feat: low level api for adding linear terms to constraints

optlang/glpk_interface.py
This is a small fix that makes sure that GLPK does not get stuck with an invalid basis (which sometimes happens for no good reason).
=> Help GLPK out of its own undefined mess

.travis.yml, optlang/interface.py, optlang/util.py, setup.py, tests/test_io.py
JSON serialisation for Variable, Constraint, Objective and Model
json_obj = model.to_json()
model_copy = Model.from_json(json_obj)
=> Model JSON storage

optlang/cplex_interface.py, optlang/glpk_interface.py
avoid getting ResourceWarning: unclosed file <_io.TextIOWrapper name='/var/folders/8q/pmqzt4t154zc6v0scntzjcs12ytkzz/T/tmpz9vozbwl.glpk' mode='w' encoding='UTF-8'>
=> use context handler to close file handles

optlang/cplex_interface.py, tests/test_cplex_interface.py, tests/test_glpk_interface.py
Fix cplex interface so variable and constraint bounds can be set to None (unconstrained)
=> Fix none bounds

optlang/cplex_interface.py, optlang/glpk_interface.py, optlang/gurobi_interface.py, optlang/util.py
=> fix: replace mktemp with NamedTemporaryFile with delete=True

optlang/glpk_interface.py, optlang/tests/abstract_test_cases.py
primal_values, dual_values, shadow_prices, reduced_costs
=> Small fix 1

optlang/__init__.py, optlang/duality.py, optlang/tests/test_duality.py
Added a duality module, which so far only contains a function for converting a continuous linear problem into its dual.
=> Dualize model

.travis.yml, docs/source/index.rst, docs/source/installation.rst, optlang/cplex_interface.py, optlang/glpk_interface.py, optlang/gurobi_interface.py, optlang/interface.py, optlang/scipy_interface.py, optlang/tests/abstract_test_cases.py, optlang/tests/test_glpk_interface.py, optlang/tests/test_interface.py
Rename dual_values to constraint_values
Rename glpk index attributes to _index
Add a Variable.set_bounds method that allows both bounds to be changed without worrying about the current bounds
=> Small fixes and additions

paper/paper.md
I made some minor writing fixes, to be adopted before acceptance in JOSS (https://github.com/openjournals/joss-reviews/issues/139)
=> Some minor writing fixes

optlang/glpk_interface.py
hot fix for recursion problem with glpk interface
=> Fix recursion bug in glpk_interface

optlang/cplex_interface.py, optlang/interface.py, optlang/scipy_interface.py, optlang/tests/abstract_test_cases.py, optlang/tests/test_cplex_interface.py
=> Fix cplex change var name

optlang/cplex_interface.py, optlang/glpk_interface.py, optlang/gurobi_interface.py, optlang/interface.py, optlang/scipy_interface.py, optlang/tests/abstract_test_cases.py, optlang/tests/test_cplex_interface.py, optlang/tests/test_glpk_interface.py, optlang/tests/test_gurobi_interface.py
Implement get_linear_coefficients methods for constraints and objectives
=> Get linear coefficients from solver

optlang/cplex_interface.py, optlang/glpk_interface.py, optlang/gurobi_interface.py, optlang/interface.py, optlang/scipy_interface.py, optlang/tests/abstract_test_cases.py, optlang/tests/test_cplex_interface.py, optlang/tests/test_glpk_interface.py, optlang/tests/test_gurobi_interface.py, optlang/util.py
fix: allow all numeric types
feat: get_linear_coefficients methods
fix: correct primal values from glpk mip
=> get_linear_coefficients and fixes

optlang/interface.py, optlang/tests/abstract_test_cases.py
=> Fix constraint bounds issue

optlang/cplex_interface.py, optlang/glpk_interface.py, optlang/gurobi_interface.py, optlang/scipy_interface.py
The sloppy argument was not always being properly passed to the super methods
=> Fix sloppy bugs

optlang/cplex_interface.py, optlang/glpk_interface.py, optlang/gurobi_interface.py, optlang/interface.py, optlang/tests/abstract_test_cases.py, optlang/tests/test_cplex_interface.py, optlang/tests/test_glpk_interface.py, optlang/tests/test_gurobi_interface.py, optlang/tests/test_scipy_interface.py, optlang/util.py
In model.configuration.tolerances
=> Interface to tolerance parameters

optlang/cplex_interface.py, optlang/expression_parsing.py, optlang/glpk_interface.py, optlang/gurobi_interface.py, optlang/scipy_interface.py, optlang/tests/abstract_test_cases.py, optlang/tests/test_expression_parsing.py
Handle constant terms in objectives
=> Objective constant terms

.travis.yml, optlang/interface.py, optlang/symbolics.py
Automatically run test suite with and without symengine. Necessary for official symengine support
=> Test symengine on travis

optlang/cplex_interface.py, optlang/glpk_interface.py, optlang/gurobi_interface.py, optlang/interface.py, optlang/scipy_interface.py, optlang/tests/abstract_test_cases.py, optlang/util.py
Fix a few overdue bugs:
- Updating variable names in Gurobi does not propagate (#195)
- conflict involving symengine and Gurobi (#198)
- Objective value not updated during optimize() (#200)
=> Bug fixes (WIP)

.travis.yml, README.rst, optlang/glpk_interface.py
Addresses #196 
I've also removed unused imports of collections and enabled testing for Py3.7
Any chance a release for Py3.7 could be made?
=> Fix collections DeprecationWarning

src/optlang/tests/abstract_test_cases.py, tox.ini
=> Remove deprecated deps in CI

README.rst, examples/simple.py, setup.cfg, src/optlang/__init__.py, src/optlang/coinor_cbc_interface.py, src/optlang/cplex_interface.py, src/optlang/glpk_exact_interface.py, src/optlang/glpk_interface.py, src/optlang/gurobi_interface.py, src/optlang/interface.py, src/optlang/scipy_interface.py, src/optlang/symbolics.py, src/optlang/tests/abstract_test_cases.py, src/optlang/tests/data/parse_the_final_netlib_results.py, src/optlang/tests/test_coinor_cbc_interface.py, src/optlang/tests/test_gurobi_interface.py, src/optlang/tests/test_hybrid_interface.py, src/optlang/tests/test_util.py
=> remove dependency on six
