opencobra/optlang

- optlang/cplex_interface.py
- optlang/glpk_interface.py
Don’t evaluate constraint expressions when building model, since they
will be constructed lazily when needed.
> Speed up unpickling

- optlang/interface.py
By calling self.constraints in line 1121 it was starting a never ending recursion.
> Fix: remove large number of constraints

- optlang/cplex_interface.py
- optlang/interface.py
- optlang/tests/abstract_test_cases.py
- optlang/util.py
Both variable and constraint bounds can now be set to sympy.Number types
> fix: allow sympy.Number to be used as bounds

- appveyor.yml
- appveyor/install.ps1
- appveyor/run_with_env.cmd
- optlang/cplex_interface.py
- optlang/glpk_interface.py
- optlang/gurobi_interface.py
- optlang/tests/test_scipy_interface.py
- tox.ini
* bugfix: NamedTemporaryFile can't be opened twice
..on Windows we get
self = <optlang.glpk_interface.Model object at 0x09695550>
def _glpk_representation(self):
with tempfile.NamedTemporaryFile(suffix=".glpk", delete=True) as tmp_file:
tmp_file_name = tmp_file.name
glp_write_prob(self.problem, 0, tmp_file_name)
>           with open(tmp_file_name) as tmp_file:
E           IOError: [Errno 13] Permission denied: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\tmptwsotv.glpk'
solution found in
http://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file
* fix: bug in gurobi interface
* fix: missing flush commands for py27
* fix also read-mode files can't be opened twice
* feat: use appveyor for basic testing on windows
doesn't use scipy as seems complicated to …
> bugfix: NamedTemporaryFile can't be opened twice (#34)

- optlang/cplex_interface.py
- optlang/glpk_interface.py
- optlang/gurobi_interface.py
- optlang/interface.py
- optlang/tests/abstract_test_cases.py
- optlang/util.py
Models can now be cloned using an LP format intermediate. iJO1366 can be cloned in <500 ms.
If a solver interface doesn’t support LP formats, the old clone method will be used.
> Clone with lp format

- optlang/cplex_interface.py
- optlang/glpk_interface.py
- optlang/gurobi_interface.py
- optlang/interface.py
Fixes #41
Using sloppy=True when constructing objectives will bypass validation of the expression (i.e. is_Linear and is_Quadratic)
> Fix recursion error

- optlang/interface.py
- optlang/tests/abstract_test_cases.py
Using LP format as intermediate has problems on cross-solver clones.
> fix: make model.Clone use json as default

- optlang/interface.py
Only update the _variables_to_constriants_mapping dict when new_name !=
old_name
> Fix bug with changing var names

- optlang/cplex_interface.py
- optlang/glpk_interface.py
- optlang/gurobi_interface.py
- optlang/interface.py
- optlang/tests/abstract_test_cases.py
- optlang/tests/test_cplex_interface.py
- optlang/tests/test_scipy_interface.py
Chore: Raise a ValueError when trying to get constraint or variable dual values for an integer problem (instead of returning None)
Fix: Adds functionality to automatically change the type of the cplex problem when changing variable types
> Fix MIP dual value behaviour

- optlang/cplex_interface.py
- optlang/exceptions.py
- optlang/tests/test_cplex_interface.py
Discussion has happened mostly in #94. This is a new PR cherry picking from that one.
> Catch Cplex errors and raise `optlang.SolverError`

- optlang/glpk_interface.py
Fixes #99. Makes the function respect the `variables` arg instead of ignoring it.
> Fix for GLPK Constraint.get_linear_coefficients

- optlang/cplex_interface.py
- optlang/glpk_interface.py
- optlang/interface.py
Implemented
`_get_primal_values()`, `_get_constraint_values()`, `_get_reduced_costs()` and `_get_shadow_prices()` and updated respective interfaces.
see 
https://github.com/biosustain/optlang/issues/98
> Model vector access

- optlang/cplex_interface.py
- optlang/glpk_interface.py
- optlang/interface.py
Rounding primals requires a more accurate tolerance threshold and should already be handled
by the solver
> Disable _round_primal_to_bounds

- optlang/gurobi_interface.py
Fixes #123.
Before:
```Python
In [1]: import optlang
In [2]: import pickle
In [3]: mod = optlang.gurobi_interface.Model()
Academic license - for non-commercial use only
In [4]: x = pickle.dumps(mod)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-82cf2f51c584> in <module>()
----> 1 x = pickle.dumps(mod)
AttributeError: Can't pickle local object 'Configuration._tolerance_functions.<locals>.<lambda>'
```
After:
```Python
In [1]: import optlang
In [2]: import pickle
In [3]: mod = optlang.gurobi_interface.Model()
Academic license - for non-commercial use only
In [4]: x = pickle.dumps(mod)
In [5]: len(x)
Out[5]: 679
```
> Make gurobi models pickeable

- optlang/gurobi_interface.py
Basically the following call stack was possible before:
```txt
model.update -> model._remove_variables ->  model.objective._get_expression -> model.variables -> model.update
```
which is a loop.
Now fixed so `Objective._get_expression` uses `model._variables` instead.
Should fix #119.
> Fix infinite recursion in gurobi interface

- optlang/gurobi_interface.py
Newer Gurobi version throw an `AttributeError` and not a `GurobiError`.
The following now works as intended:
```Python
In [1]: import optlang
In [2]: gurobi = optlang.gurobi_interface
In [3]: mod = gurobi.Model()
Academic license - for non-commercial use only
In [4]: v = gurobi.Variable(name="v", lb=0, ub=3)
In [5]: mod.objective = gurobi.Objective(v, direction="max")
In [6]: mod.optimize()
Out[6]: 'optimal'
In [7]: mod.objective.value
Out[7]: 3.0
In [8]: v.lb = 1
In [9]: mod.objective.value is None
Out[9]: True
```
Before the fix the last statement would throw an AttributeError.
> Fix uncaught error when requesting invalidated objective

- optlang/gurobi_interface.py
Now gives the correct primals for the constraint expression:
```Python
In [1]: import optlang
In [2]: gurobi = optlang.gurobi_interface
In [3]: mod = gurobi.Model()
Academic license - for non-commercial use only
In [4]: x = gurobi.Variable(lb=3, ub=3, name="x")
In [5]: const = gurobi.Constraint(x, lb=3)
In [6]: mod.add([x, const])
In [7]: mod.optimize()
Out[7]: 'optimal'
In [8]: x.primal
Out[8]: 3.0
In [9]: const.primal
Out[9]: 3.0
```
Fixes #115.
> Fix constraint primal calculation in gurobi interface

- optlang/interface.py
- optlang/tests/test_interface.py
Variables with empty names trigger's segfaults in glpk
interface. Easiest fix appears to simply not allow them as anyway not
meaningful.
> fix: ensure that variable names are not empty str

- optlang/cplex_interface.py
- optlang/duality.py
- optlang/glpk_interface.py
- optlang/gurobi_interface.py
- optlang/symbolics.py
- optlang/tests/abstract_test_cases.py
- optlang/tests/test_expression_parsing.py
- optlang/tests/test_scipy_interface.py
- Make gurobi models picklable
- Fix gurobi infinite recursion
- Fix gurobi constraint primal calculation
- Fix a bug where cplex took forever to set a large objective (e.g. 10000 vars)
- Fix some issues with symengine compatibility
> Various bug fixes

- optlang/symbolics.py
This adds the `Basic` and `Number` types to `optlang.symbolics`. This is needed in order to remain compatible with cobrapy.
Thanks!
> Add basic types to optlang.symbolics

- optlang/symbolics.py
There is a small error (missing unpacking of the args) which will cause `symbolics.mul` to fail for basically any input.
> repair symbolics.mul for symengine

- optlang/glpk_exact_interface.py
- optlang/glpk_interface.py
- optlang/tests/test_glpk_exact_interface.py
- optlang/tests/test_glpk_interface.py
- optlang/tests/test_netlib_glpk_exact_interface.py
This is one option. Another way of doing this could be to add another method to the model `Model` class, for example `model.optimize_exact` or a kwarg like `model.optimize(exact=True)` that some solvers might support or not. I kinda prefer this more explicit way of doing it though.
> Add an interface to GLPK's exact solver

- examples/simple_numpy.py
Is this helpful? I think its nice to see that optlang symbolics play nicely with numpy datatypes. 
Is there a better way to create a vector of symbols?
> adding simple example using numpy linear algebra

- optlang/cplex_interface.py
- optlang/interface.py
- optlang/tests/abstract_test_cases.py
I am not sure this is a good solution. Also, need to extend solution in
case we're adding support for quadratic constraints.
> Fix #140 – indicator constraints not being removed

- .travis.yml
- appveyor.yml
* Add Python 3.6 to tested versions.
* Abort testing as soon as one test fails (`fast_finish`).
* Add the Python version to the conditions such that only one deployment is attempted.
> fix: make releases from only one Python version

- docs/source/conf.py
- requirements_rtd.txt
Replaced numpydoc with napoleon (which comes prepackaged with sphinx now). Did the fix based on this issue here https://github.com/rtfd/readthedocs.org/issues/4057.
> fix: broken rtfd build due to numpydoc getting old

- optlang/cplex_interface.py
The current behaviour will overwrite the root logger level of any application using optlang together with cplex (in practice silence most log output and confuse developers). This fix creates a logger with an explicit name instead of using root. I chose `cplex.problem` instead of `__name__` since it's not actually a logger for the current module; not 100% sure what the best name is though.
> Set cplex problem logger name

- optlang/expression_parsing.py
- optlang/scipy_interface.py
- optlang/symbolics.py
- optlang/tests/abstract_test_cases.py
- optlang/tests/test_symbolics.py
Using real numbers avoids certain corner cases where integers are either
undesired, e.g., in `set_linear_coefficients` or they would be
simplified out as in `Mul(One, variable)`.
> refactor: make base constants real numbers

- optlang/cplex_interface.py
The deprecation warnings are creating some noise in our applications :)
> Don't use deprecated `logging.warn` method

- optlang/cplex_interface.py
- optlang/glpk_interface.py
- optlang/interface.py
- optlang/util.py
This fixes #188:
```Python
In [1]: from cobra.test import create_test_model                                                                                                                              
In [2]: solver = create_test_model("textbook").solver                                                                                                                         
In [4]: solver.configuration.tolerances.feasibility = 1e-5                                                                                                                    
In [5]: import pickle                                                                                                                                                         
In [6]: pickled = pickle.dumps(solver) …
```
> Conserve tolerances in GLPK when pickling

- optlang/tests/test_glpk_interface.py
Hi all,
I wrote a couple of tests to check if the feasibility tolerance is preserved when pickling and cloning a configuration object in the glpk interface. This PR would require prior merge of #189.
Best,
Justin
> Test for cloning and pickling configuration object in GLPK interface

- .travis.yml
- appveyor.yml
- setup.py
- tox.ini
Fix build for 13673ac26f6b3ba37a2ef392489722c52e3c5ff1.
The build is failing because colorama no longer supports python 3.4. The latest version to support it is [colorama 0.3.9](https://github.com/tartley/colorama/blob/master/CHANGELOG.rst).
> fix: pin colorama version

- src/optlang/cplex_interface.py
- src/optlang/glpk_interface.py
- src/optlang/gurobi_interface.py
- src/optlang/tests/test_change_solver.py
Fixes the second error described in #220 
When cloning a model to another solver, the tolerances get set on the new model. However, when solvers have different tolerance parameters, this resulted in an AttributeError. This fix will ignore these AttributeErrors, and the result is that only the tolerance parameters that are shared between the old and new solver will get set on the cloned model.
A test for cloning models between solvers was also fixed to correctly test the case where a cplex model is cloned to a glpk model.
> Fix clone tolerance error

- README.rst
- docs/source/index.rst
- docs/source/installation.rst
- setup.cfg
- src/optlang/__init__.py
- src/optlang/cplex_interface.py
- src/optlang/glpk_interface.py
- src/optlang/osqp_interface.py
- src/optlang/tests/abstract_test_cases.py
- src/optlang/tests/test_osqp_interface.py
- src/optlang/util.py
- tox.ini
This is a first working version of a QP solver via [OSQP](https://osqp.org). OSQP expects the problem to be sparse and static so I added a thin compatibility layer that manages the OSQP problem via dictionaries. All operations on that layer are at worst O(nv + nc) but it makes problem setup about 10-20% of the entire solve time for most models. Could maybe be optimized more in the future but should be sufficient for now. Still need to add tests but I added some more complicated models to the test data for now.
It now supports all features such as reduced costs etc. This version is also faster than the previous PR since it gets primals and duals via the C interface instead of evaluating expressions. We used it in the recent MICOM course and it worked well.
Demo:
```bash
Python 3.9.1 …
```
> Add QP solver through OSQP

- .github/workflows/main.yml
- src/optlang/tests/test_netlib_cplex_interface.py
- src/optlang/tests/test_netlib_glpk_interface.py
- src/optlang/tests/test_netlib_gurobi_interface.py
- tox.ini
This is supposed to fix the CI failures with OSQP. Python 3.9 requires osqp>=0.6.2 but Python 2.7 will only work with osqp<=0.6.1.
> Fix CI for OSQP and Python 3.9

- src/optlang/glpk_interface.py
- enables setting the integrality threshold for GLPK again
- changes the default for presolving for *MIP* problems in GLPK
This is now the same default as in GLPK and is recommended since the MIP solver becomes very unstable otherwise. 
- made glpk_interface.py pep8 compliant
> Improvements to GLPK configuration for MIPs

- CHANGELOG.rst
- src/optlang/gurobi_interface.py
- src/optlang/osqp_interface.py
- src/optlang/symbolics.py
- src/optlang/tests/test_gurobi_interface.py
- src/optlang/tests/test_osqp_interface.py
- tox.ini
This PR fixes several issues with Gurobi and a bug where one could not clone from the OSQP interface. 
- renaming variables was broken due to an obsolete workaround (fixed in Gurobi 9.1), now works
- now correctly serializes the configuration in the Gurobi interface (fixes pickling)
- added a pickling test for gurobi
- fixes 2 broken tests for Gurobi
- fixed the shim for the integrality tolerance in osqp_interface so it can be cloned to other interfaces
<details>
```
============================================================================ test session starts =============================================================================
platform linux -- Python 3.7.10, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /users/cdiener/optlang, configfile: tox.ini, testpaths: …
```
> Fixes for the gurobi interface and OSQP tolerances

- CHANGELOG.rst
- src/optlang/glpk_interface.py
While looking at fixing the GLPK scaling output I noticed that problem scaling actually did not take in the right place. The problem has to be scaled after it is fully built, however scaling was often performed before adding variables and constraints which has no effect. The best place to scale is before optimization as it ensures that the model is built and all changes are applied.
As a side effect that now also respects the verbosity output for scaling.
Example:
```
Python 3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from cobra.io import load_model
In [2]: mod = load_model("textbook")
In [3]: mod.solver = "glpk"
In [4]: # note that there was no …
```
> move GLPK scaling to the right place

- CHANGELOG.rst
- src/optlang/symbolics.py
Small fix that makes the exports for symbolics a bit more consistent. In particular doing something like:
```python
from optlang.symbolics import Expr
```
will no longer fail on symengine but work on sympy.
> add consistent exports for the symbolics module

- .github/workflows/main.yml
- CHANGELOG.rst
- setup.cfg
- src/optlang/interface.py
- src/optlang/scipy_interface.py
- src/optlang/symbolics.py
- src/optlang/tests/test_io.py
- tox.ini
Some changes in sympy 1.12 broke the previous hack in place to make the optlang `Symbol` class unique. However, sympy now has the `Dummy` class for a Symbol where symbols with the same name are unique, so we now derive from that class. Symengine `Symbols` are unique by default, so no changes here.
Also fixes some warnings due to updates in jsonschema and scipy.
> several fixes to support upstream changes

- .github/workflows/main.yml
- CHANGELOG.rst
- setup.cfg
- src/optlang/matrix_interface.py
- src/optlang/osqp_interface.py
- src/optlang/tests/test_osqp_interface.py
- tox.ini
This is a proposed refactor of the OSQP interface into a generic solver interface for backends that assume immutable problems in (sparse) standard form. This should make it much easier to port solvers to optlang and would for instance be useful to create compatibility with PULP or CVXPY or any other solver that is based on a matrix formulation of the problem. This is also supposed to set the stage for a future [HIGHS/OSQP hybrid solver](https://github.com/cdiener/optlang/tree/feature/hybrid_solver) I would like to add. 
The interface is still somehwat performant by creating a fast intermediate layer that can be translated into sparse matrices quickly.
> Refactor OSQP interface into a generic matrix solver

- src/optlang/gurobi_interface.py
Because MIPs lose convexity, shadow prices and reduced costs aren't available for them until the model was relaxed (variables transformed and general constraints removed) or fixed (fixes integer values to the best solution found). That means that it is necessary for the functions `_get_reduced_costs` and `_get_shadow_prices` to not only check if the problem is a pure integer problem but also if the model is a mixed integer problem. For that, another property `is_mip` was introduced.
> Add MIP check in gurobi interface and update shadow_prices and reduced_cost to throw proper error if MIP 

- CHANGELOG.rst
- src/optlang/matrix_interface.py
- tox.ini
This replaces `np.Infinity` with the backwards compatible `np.inf`.
> [fix] Make the hybrid interface work for numpy>=2.0

- .github/workflows/cron.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- README.rst
- setup.cfg
Upgrade the GitHub workflows in the following ways:
* Create a reusable test workflow
* Run tests on push and PR
* Run release on pushed tags
* Run a weekly test job, so we can notice problems sooner
* Rely on OIDC tokens for publishing to PyPI
> Upgrade GitHub workflows

- CHANGELOG.rst
- src/optlang/tests/abstract_test_cases.py
- src/optlang/tests/test_hybrid_interface.py
This fixes #268. I opted for the expand->evalf because it works with sympy and symengine without adding new sympy imports (because the plan is to drop the hard sympy req in the future).
Also fixed another instance of this in the hybrid solver tests.
> Fix test for objective offset

- src/optlang/tests/test_glpk_exact_interface.py
- src/optlang/tests/test_glpk_interface.py
Just fixing another instance here. Bit surprised that this occured in the exact solver too though. This one should have a stricter tolerance by default.
> fix floating point accurcy

- CHANGELOG.rst
- src/optlang/gurobi_interface.py
This is a simple fix to enable compatibility with Gurobi 12.0. The change is backwards compatible to prior Gurobi versions.
> Make optlang compatible with Gurobi 12.0

- src/optlang/matrix_interface.py
Corrects spelling of optimization in doc-string
Fixes escaping of latex.
This fixes the invalid escape warning about  `\m`
> Fix docstring

- CHANGELOG.rst
- src/optlang/interface.py
This fixes the issue illustrated in #271.
> Don't leave dangling refs when removing more than 350 constraints

- .github/workflows/release.yml
- .github/workflows/test.yml
- CHANGELOG.rst
- setup.cfg
- src/optlang/tests/test_container.py
- tox.ini
This updates the CI/CD to newer Python versions and limits the CPLEX, Gurobi, and MIP tests to those python versions that support them.
> Enable Python 3.13 and make tests more resilient to lacking cplex/gurobi wheels
